spa_app/urls.py
from django.contrib import admin
from django.urls import path

from appointments import views
import appointments

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('appointments/', views.appointments, name='appointments'),
    path('edit_appointment/', views.edit_appointment, name='edit_appointment'),
    path('appointments_admin/', views.appointments_admin, name='appointments_admin'),
    path('edit_appointment_admin/', views.edit_appointment_admin, name='edit_appointment_admin'),
]

appointments/models.py
from django.db import models

# Create your models here.

GENDERS =[
    ( 'Male'   , 'M'),
    ( 'Female' , 'F'),
    ( 'Other'  , 'O')
]

TYPE_USER =[
    ( 'Admin'  , 'A'),
    ( 'Normal' , 'N')
]

SERVICES =[
    ( 'Massage'                , 'Massage' ),
    ( 'Manicure'               , 'Manicure' ),
    ( 'Pedicure'               , 'Pedicure' ),
    ( 'Facial Cleansing'       , 'Facial Cleansing' ),
    ( 'Permanent Hair Removal' , 'Permanent Hair Removal' ),
    ( 'Cryotherapy'            , 'Cryotherapy' )
]

TIME = [
    ( '8:00 AM' , '8:00 AM' ),
    ( '9:00 AM' , '9:00 AM' ),
    ( '10:00 AM', '10:00 AM'),
    ( '11:00 AM', '11:00 AM'),
    ( '1:00 PM' , '1:00 PM'),
    ( '2:00 PM' , '2:00 PM'),
    ( '3:00 PM' , '3:00 PM'),
    ( '4:00 PM' , '4:00 PM'),
]

ESTETICIANS = [
    ( 'José López', 'José López'),
    ( 'Mariela Hernández', 'Mariela Hernández')
]

class User(models.Model):
    id = models.AutoField(primary_key=True)
    type_user =  models.CharField(max_length=7, choices=TYPE_USER)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    gender = models.CharField(max_length=6, choices=GENDERS)
    age = models.PositiveIntegerField(blank=True)
    telephone = models.PositiveIntegerField(blank=True)
    email = models.EmailField(max_length=254, unique=True)
    password =  models.CharField(max_length=10)

class Appointment(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    estetician = models.CharField(max_length=25, choices=ESTETICIANS)
    service = models.CharField(max_length=25, choices=SERVICES)
    date = models.DateField()
    time = models.CharField(max_length=10, choices=TIME)

class Login(models.Model):
    email = models.EmailField(max_length=254, unique=True)
    password = models.CharField(max_length=10)

appointments/forms.py
from django import forms
from .models import User
from .models import Appointment
from .models import Login
from django.forms import PasswordInput

class LoginForm(forms.ModelForm):
    class Meta:
        model = Login
        fields = [
            'email',
            'password',
            ]

class UserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.required = True
    class Meta:
        model = User
        fields = [
            'type_user',
            'first_name',
            'last_name',
            'gender',
            'age',
            'telephone',
            'email',
            'password',
        ]

class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = [
            'id',
            'user_id',
            'estetician',
            'service',
            'date',
            'time',
        ]

appointments/views.py
from django.db.models.fields import EmailField
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, render
from django.http import HttpResponse
from django.contrib import messages
from .forms import UserForm, LoginForm
from .forms import AppointmentForm
from .models import User
from .models import Appointment

TIME = [
    ('8:00 AM', 'José López'),
    ('8:00 AM', 'Mariela Hernández'), 
    ('9:00 AM' , 'José López'),
    ('9:00 AM' , 'Mariela Hernández'),
    ('10:00 AM' , 'José López'),
    ('10:00 AM' , 'Mariela Hernández'),
    ('11:00 AM' , 'José López'),
    ('11:00 AM' , 'Mariela Hernández'),
    ('1:00 PM' , 'José López'),
    ('1:00 PM' , 'Mariela Hernández'),
    ('2:00 PM' , 'José López'),
    ('2:00 PM' , 'Mariela Hernández'),
    ('3:00 PM' , 'José López'),
    ('3:00 PM' , 'Mariela Hernández'),
    ('4:00 PM' , 'José López'),
    ('4:00 PM' , 'Mariela Hernández') ]


# Create your views here.
def home(request):
    form = LoginForm()
    error = {}
    client_list = get_appointment_clients()
    appointments_list = []
    request.session.flush()
    if request.method == 'POST':
        try:
            form = LoginForm(request.POST)
            if form.is_valid():
                f_email = str(form.cleaned_data['email'])
                f_passw = str(form.cleaned_data['password'])
                user    = User.objects.raw('SELECT * FROM appointments_user WHERE email = %s', [f_email])
                if user[0] is not None:

                    if user[0].password == f_passw:
                        request.session['user'] = user[0].id
                        form = AppointmentForm()
                        if user[0].type_user == 'Admin':
                            appointments_usr  = get_appointments_admin(request)
                            return HttpResponseRedirect("../appointments_admin/")
                            
                        else:
                            appointments_usr  = get_appointments(request)
                            return HttpResponseRedirect("../appointments/")
                    else:
                        error['password'] = "Incorrect password"
                else:
                    error['email'] = "Email doesn't exist"
            else:
                error['password'] = "Some field is missing"
            return render(request, 'home.html', {'form': form, 'error': error})
        except:
            form = LoginForm()
            print("except")
            error['email'] = "Email doesn't exist"
            return render(request, 'home.html', {'form': form, 'error': error})
    else:
        return render(request,'home.html', {'form': form})

def register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'home.html', {'form': form})
        else:
            return render(request,'register.html', {'form': form})
    else:
        form = UserForm()
        return render(request,'register.html', {'form': form})

def appointments(request):

    appointments_usr  = get_appointments(request)
    appointments_list = []
    error = {}
    if request.method=='POST' and 'check_btn' in request.POST:
        form = AppointmentForm()
        try:
            request.session['date'] = request.POST['date']
            appointments_by_date = get_appointments_by_date_and_user(request)

            temp_TIME = TIME.copy()

            for i in appointments_by_date:
                if i in temp_TIME:
                    temp_TIME.remove(i)

            appointments_list = []
            for i in temp_TIME:
                appointments_list.append(f'{i[0]} with {i[1]}') 
        
            return render(request, 'appointments.html', {'form': form ,'appointment_list': appointments_list,  'appointments_usr': appointments_usr})
        except:

            return render(request, 'appointments.html', {'form': form ,'appointment_list': appointments_list,  'appointments_usr': appointments_usr})

    elif request.method == 'POST' and 'reserve_btn' in request.POST:
        form = AppointmentForm()
        try:
            info = request.POST['appointments'].split(sep=' with ')
        
            updated_request  = request.POST.copy()
            updated_request.update({
                'user_id': request.session['user'],
                'date': request.session['date'],
                'time': info[0],
                'estetician': info[1],
                'service': request.POST['service']
            })
            form = AppointmentForm(updated_request)
          
            if form.is_valid():
                form.save()
                appointments_list = get_appointments(request)
                appointments_usr = get_appointments(request)
                del request.session['date']
                return render(request, 'appointments.html', {'form': form ,'appointments_list': appointments_list, 'appointments_usr': appointments_usr})
            else:
                form = AppointmentForm()
                return render(request,'appointments.html', {'form': form ,'appointments_list': appointments_list, 'appointments_usr': appointments_usr})
        except:
            error['date'] = "Please select a date"
            return render(request, 'appointments.html', {'form': form ,'appointments_list': appointments_list, 'appointments_usr': appointments_usr, 'error':error})

    
    elif request.method=='POST' and 'delete_btn' in request.POST:
        # Se lee el id de la cita del request
        appointment_id = request.POST['appointment_id']

        # Se elimina la cita utilizando el id
        Appointment.objects.filter(id=appointment_id).delete()

        # Se actualiza la tabla de citas
        appointments_list = get_appointments(request)
        
        appointments_usr = get_appointments(request)

        form = AppointmentForm()
        return render(request, 'appointments.html', {'form': form ,'appointments_usr': appointments_usr})

    
    elif request.method=='POST' and 'edit_btn' in request.POST:
        form = AppointmentForm()
        request.session['appointment_id'] = request.POST['appointment_id']
        return HttpResponseRedirect("../edit_appointment/")
    
    else:
        appointments_list = get_appointments(request)
        form = AppointmentForm()
        return render(request, 'appointments.html', {'form': form ,'appointments_usr': appointments_usr})
    

def appointments_admin(request):
    client_list = get_appointment_clients()
    appointments_usr  = get_appointments_admin(request)
    appointments_list = []
    error = {}

    if request.method=='POST' and 'check_btn' in request.POST:
        form = AppointmentForm()
        try:
            request.session['date'] = request.POST['date']
            appointments_by_date = get_appointments_by_date(request)

            temp_TIME = TIME.copy()

            for i in appointments_by_date:
                if i in temp_TIME:
                    temp_TIME.remove(i)

            appointments_list = []
            for i in temp_TIME:
                appointments_list.append(f'{i[0]} with {i[1]}') 

            return render(request, 'appointments_admin.html', {'form': form ,'appointment_list': appointments_list,  'appointments_usr': appointments_usr, 'client_list': client_list})
        except:

            return render(request, 'appointments_admin.html', {'form': form ,'appointment_list': appointments_list,  'appointments_usr': appointments_usr, 'client_list': client_list})

    elif request.method == 'POST' and 'reserve_btn' in request.POST:
        form = AppointmentForm()
        try:
            info = request.POST['appointments'].split(sep=' with ')
            info_client = request.POST['user_sel'].split(sep=': ')
            id_client = int(info_client[0])
            
            updated_request  = request.POST.copy()
            updated_request.update({
                'user_id': id_client,
                'date': request.session['date'],
                'time': info[0],
                'estetician': info[1],
                'service': request.POST['service']
            })
            form = AppointmentForm(updated_request)
          
            if form.is_valid():
                form.save()
                appointments_usr = get_appointments_admin(request)
                del request.session['date']
                return render(request, 'appointments_admin.html', {'form': form ,'appointments_list': appointments_list, 'appointments_usr': appointments_usr, 'client_list': client_list})
            else:
                form = AppointmentForm()
                return render(request,'appointments_admin.html', {'form': form ,'appointments_list': appointments_list, 'appointments_usr': appointments_usr, 'client_list': client_list})
        except:
            error['date'] = "Please select a date"
            return render(request, 'appointments_admin.html', {'form': form ,'appointments_list': appointments_list, 'appointments_usr': appointments_usr, 'client_list': client_list, 'error': error})

    
    elif request.method=='POST' and 'delete_btn' in request.POST:
        # Se lee el id de la cita del request
        appointment_id = request.POST['appointment_id']

        # Se elimina la cita utilizando el id
        Appointment.objects.filter(id=appointment_id).delete()

        # Se actualiza la tabla de citas
        appointments_list = get_appointments_admin(request)
        
        appointments_usr = get_appointments_admin(request)
        
        form = AppointmentForm()
        return render(request, 'appointments_admin.html', {'form': form ,'appointments_usr': appointments_usr, 'client_list': client_list})
    
    elif request.method=='POST' and 'edit_btn' in request.POST:
        form = AppointmentForm()
        request.session['appointment_id'] = request.POST['appointment_id']

appointments/templates/appointments.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Appointments</title>
    <!-- NAVIGATION -->
    <link rel="stylesheet" href="https://bootswatch.com/4/lux/bootstrap.min.css">
  </head>
  <body background="https://www.elementsspacr.com/wp-content/uploads/2017/08/spa-elements.jpg">
    <!-- navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="../home">Log Out</a>
    </nav>
</br>
<center><h2>Appointment Manager</h2></center>

<div class="container mt-5">
  <div class="row">
    <div class="col-md-7">
      <table class="table table-bordered" style="background-color: white">
        <thead>
          <tr>
            <td>ID</td>
            <td>Estetician</td>   
            <td>Service</td>
            <td>Date</td>
            <td>Time</td>
          </tr>
        </thead>
        <tbody>
          {% for appointment in appointments_usr %}
            <tr>
              <td> {{appointment.id}}</td>
              <td> {{appointment.estetician}}</td>
              <td> {{appointment.service}}</td>
              <td> {{appointment.date}}</td>
              <td> {{appointment.time}}</td>
            <tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="col-md-5">
      <div class="card-body">

        <form action="../appointments/" method="POST">
          {% csrf_token %} 
          <center><h3>Register Appointment</h3></center>
          <div class="form-group row">
            <label for="id_date" class="col-2 col-form-label">Date</label>
            <div class="col-10">
              <input class="form-control" type="date" id="id_date" name="date">
            </div>
          </div>

          <center>
            <button type="submit" class="btn btn-primary btn-block" name="check_btn" >Check Availability</button>
          </center>

        </form>

        <div class="row" >
          <div class="card-body">
            <form action="../appointments/" method="POST">
              {% csrf_token %} 
              </br>
              <div class="form-group row">
                <input type="hidden" id="id_user_id" name="user_id" value={{ request.session.user }}>
              </div>
              <div class="form-group row">
                <label for="id_appointments" class="col-2 col-form-label">Appts.</label>
                <div class="col-10">  
                  <select class="form-control" id="id_appointments" name="appointments" >
                    {% for p in appointment_list %}
                      <option>{{p}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <div class="form-group row">
                <label for="id_service" class="col-2 col-form-label">Service</label>
                <div class="col-10">  
                  <select class="form-control" id="id_service" name="service" >
                    <option>Massage</option>
                    <option>Manicure</option>
                    <option>Pedicure</option>
                    <option>Facial Cleansing</option>
                    <option>Permanent Hair Removal</option>
                    <option>Cryotherapy</option>
                  </select>
                </div>
              </div>
              <center>
              <h6 for="id_error_date" class="text-danger"> {{error.date}}</h6>
              </center>
              <button type="submit" class="btn btn-primary btn-block"  name="reserve_btn" > Reserve</button>
            
            </form>
          </div>
        </div>
        
        <div class="row" >
          <div class="card-body">
            <form action="../appointments/" method="POST">
              {% csrf_token %} 
              </br>
              <center><h3>Edit Appointment</h3></center>


              <div class="form-group row">
                <label for="id_service" class="col-2 col-form-label">ID</label>
                <div class="col-10">  
                  <select class="form-control" id="id_id" name="appointment_id" >
                    {% for p in appointments_usr %}
                      <option>{{p.id}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>

              <button type="submit" class="btn btn-primary btn-block"  name="delete_btn" > Delete</button>
              <button type="submit" class="btn btn-primary btn-block" name="edit_btn" > Edit </button>
            </form>
          </div>
        </div>
      </div>
    </div>
      
  </div>
</div>
</body>
</html>

appointments/templates/appointments_admin.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Appointments</title>
    <!-- NAVIGATION -->
    <link rel="stylesheet" href="https://bootswatch.com/4/lux/bootstrap.min.css">
  </head>
  <body background="https://www.elementsspacr.com/wp-content/uploads/2017/08/spa-elements.jpg">
    <!-- navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="../home">Log Out</a>
    </nav>
</br>
<center><h2>Appointment Admin Manager</h2></center>

<div class="container mt-5">
  <div class="row">
    <div class="col-md-7">
      <table class="table table-bordered" style="background-color: white">
        <thead>
          <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Estetician</td>   
            <td>Service</td>
            <td>Date</td>
            <td>Time</td>
          </tr>
        </thead>
        <tbody>
          {% for appointment in appointments_usr %}
            <tr>
              <td> {{appointment.id}} </td>
              <td> {{appointment.name}} </td>
              <td> {{appointment.estetician}}</td>
              <td> {{appointment.service}}</td>
              <td> {{appointment.date}}</td>
              <td> {{appointment.time}}</td>
            <tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="col-md-5">
      <div class="card-body">

        <form action="../appointments_admin/" method="POST">
          {% csrf_token %} 
          <center><h3>Register Appointment</h3></center>
          <div class="form-group row">
            <label for="id_date" class="col-2 col-form-label">Date</label>
            <div class="col-10">
              <input class="form-control" type="date" id="id_date" name="date">
            </div>
          </div>

          <center>
            <button type="submit" class="btn btn-primary btn-block" name="check_btn" >Check Availability</button>
          </center>

        </form>

        <div class="row" >
          <div class="card-body">
            <form action="../appointments_admin/" method="POST">
              {% csrf_token %} 
              </br>
              <div class="form-group row">
                <input type="hidden" id="id_user_id" name="user_id" value={{ request.session.user }}>
              </div>
              <div class="form-group row">
                <label for="id_appointments" class="col-2 col-form-label">Appts.</label>
                <div class="col-10">  
                  <select class="form-control" id="id_appointments" name="appointments" >
                    {% for p in appointment_list %}
                      <option>{{p}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <div class="form-group row">
                <label for="id_service" class="col-2 col-form-label">Client</label>
                <div class="col-10">  
                  <select class="form-control" id="id_user_sel" name="user_sel" >
                    {% for p in client_list %}
                      <option>{{p}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <div class="form-group row">
                <label for="id_service" class="col-2 col-form-label">Service</label>
                <div class="col-10">  
                  <select class="form-control" id="id_service" name="service" >
                    <option>Massage</option>
                    <option>Manicure</option>
                    <option>Pedicure</option>
                    <option>Facial Cleansing</option>
                    <option>Permanent Hair Removal</option>
                    <option>Cryotherapy</option>
                  </select>
                </div>
              </div>
              <center>
              <h6 for="id_error_date" class="text-danger"> {{error.date}} </h6>
              </center>
              <button type="submit" class="btn btn-primary btn-block"  name="reserve_btn" > Reserve</button>
            </form>
          </div>
        </div>
        
        <div class="row" >
          <div class="card-body">
            <form action="../appointments_admin/" method="POST">
              {% csrf_token %} 
              </br>
              <center><h3>Edit Appointment</h3></center>


              <div class="form-group row">
                <label for="id_service" class="col-2 col-form-label">ID</label>
                <div class="col-10">  
                  <select class="form-control" id="id_id" name="appointment_id" >
                    {% for p in appointments_usr %}
                      <option>{{p.id}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>

              <button type="submit" class="btn btn-primary btn-block"  name="delete_btn" > Delete</button>
              <button type="submit" class="btn btn-primary btn-block" name="edit_btn" > Edit </button>
            </form>
          </div>
        </div>
      </div>
    </div>
      
  </div>
</div>
</body>
</html>

appointments/templates/edit_appointment.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Edit Appointments</title>
    <!-- NAVIGATION -->
    <link rel="stylesheet" href="https://bootswatch.com/4/lux/bootstrap.min.css">
  </head>
  <body background="https://www.elementsspacr.com/wp-content/uploads/2017/08/spa-elements.jpg">
    <!-- navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="../appointments">Appointments</a>
      <a class="navbar-brand" href="../home">Log Out</a>
    </nav>

</br>
</br>
<center><h2>Edit Appointment</h2></center>

<center>
<div class="container mt-5">
    <div class="row">
      <div class="col-md-5 mx-auto">
        <div class="card-body">
  
          <form action="../edit_appointment/" method="POST">
            {% csrf_token %} 
            <div class="form-group row">
              <label for="id_date" class="col-2 col-form-label">Date</label>
              <div class="col-10">
                <input class="form-control" type="date" id="id_date" name="date">
              </div>
            </div>
  
            <center>
              <button type="submit" class="btn btn-primary btn-block" name="check_btn" >Check Availability</button>
            </center>
  
          </form>
  
          <div class="row" >
            <div class="card-body">
              <form action="../edit_appointment/" method="POST">
                {% csrf_token %} 
                </br>
                <div class="form-group row">
                  <label for="id_appointments" class="col-2 col-form-label">Appts.</label>
                  <div class="col-10">  
                    <select class="form-control" id="id_appointments" name="appointments" >
                      {% for p in appointment_list %}
                        <option>{{p}}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="form-group row">
                  <label for="id_service" class="col-2 col-form-label">Service</label>
                  <div class="col-10">  
                    <select class="form-control" id="id_service" name="service" >
                      <option>Massage</option>
                      <option>Manicure</option>
                      <option>Pedicure</option>
                      <option>Facial Cleansing</option>
                      <option>Permanent Hair Removal</option>
                      <option>Cryotherapy</option>
                    </select>
                  </div>
                </div>
                <h6 for="id_error_date" class="text-danger"> {{error.date}}</h6>
                <button type="submit" class="btn btn-primary btn-block"  name="update_btn" > Update</button>
              </form>
            </div>
          </div>
  </div>
</center>

</body>
</html>

appointments/templates/edit_client.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Paciente</title>
    <!-- NAVIGATION -->
    <link rel="stylesheet" href="https://bootswatch.com/4/lux/bootstrap.min.css">
  </head>
  <body>
    <!-- navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="../appointments">Citas</a>
      <a class="navbar-brand" href="../edit_client">Perfil</a>
    </nav>

</br>
</br>
<center><h2>Perfil Paciente</h2></center>

<center>
<div class="container mt-5">
    <div class="row">
      <div class="col-md-5 offset-md-3 card">
        <div class="card-body">
          <form action="/update/<%= data.id %>" method="POST">
            <div class="form-group">
              <input type="text" name="name"  class="form-control" autofocus>
            </div>
            <div class="form-group">
              <input type="text" name="address" placeholder="Address" class="form-control">
            </div>
            <div class="form-group">
              <input type="text" name="phone" value="<%= data.phone%>" class="form-control">
            </div>
  
            <button type="submit" class="btn btn-primary">
              actualizar
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</center>

</body>
</html>

appointments/templates/register.html


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Register</title>
    <link rel="stylesheet" href="https://bootswatch.com/4/lux/bootstrap.min.css">
  </head>
  
  <body background="https://www.elementsspacr.com/wp-content/uploads/2017/08/spa-elements.jpg">
  
    <!-- navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="../home">Home</a>
    </nav>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
    <div class="row">
      <div class="col-md-4 offset-md-4 card">
        <div class="card-body">
          <form action="../register/" method="POST">
            {% csrf_token %} 
            <div class="form-group">
              <div class="row">
                <div class="col">
                  <label for="id_first_name">First name</label>
                  <input type="text" class="form-control" placeholder="First name" name="first_name"
                  id="id_first_name">
                </div>
                <div class="col">
                  <label for="id_last_name">Last name</label>
                  <input type="text" class="form-control" placeholder="Last name" name="last_name"
                  id="id_last_name">
                </div>
              </div>
            </div>
            
            <div class="form-group">
              <div class="row">
                <div class="col">
                  <label for="id_gender">Gender</label>
                  <select class="form-control" id="id_gender" placeholder="Gender" name="gender" >
                    <option>Male</option>
                    <option>Female</option>
                    <option>Other</option>
                  </select>
                </div>
                <div class="col">
                  <label for="id_age">Age</label>
                  <input type="text" name="age" placeholder="Age" class="form-control" id="id_age">
                </div>
              </div>
            </div>

            <div class="form-group">
              <div class="row">
                <div class="col">
                  <label for="id_email">Email</label>
                  <input type="email" class="form-control" id="id_email" placeholder="Email" name="email">
                </div>
                <div class="col">
                  <label for="id_telephone">Telephone</label>
                  <input type="tel" class="form-control" placeholder="(506)-5555-5555" id="id_telephone" name="telephone">
                </div>
              </div>   

            <div class="form-group">
              <div class="row">
                <div class="col">
                  <label for="id_password">Password</label>
                  <input type="password" class="form-control" id="id_password" placeholder="Password" name="password">
                </div>
                <div class="col">
                  <label for="id_type_user">Type</label>
                  <select class="form-control" id="id_type_user" name="type_user" >
                    <option>Admin</option>
                    <option>Normal</option>
                  </select>
                </div>
            </div>

              <center>
                </br>
                <button type="submit" class="btn btn-primary btn-block">Register</button>

              </center>
            </div>
            
          </form>
        </div>
      </div>
    </div>
  </div>
</body>
</html>